# This workflow will install Python dependencies and run the linter
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    name: Lint with Ruff
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.9.6
      with:
        pixi-version: v0.66.0

    - name: Run linter check
      run: |
        pixi run --environment dev ruff check KN1DPy/ --output-format=github
